01/28/2019 01:06:31 PM    ==== Scoary started ====
01/28/2019 01:06:31 PM    Command: /home/hermuba/miniconda3/bin/scoary -g /home/hermuba/data0118/scoary/gene_abs.Rtab -t /home/hermuba/data0118/scoary/scoary_trait.csv -s 2
01/28/2019 01:06:31 PM    Reading gene presence absence file
01/28/2019 01:06:31 PM    CRITICAL:
Traceback (most recent call last):
  File "/home/hermuba/miniconda3/lib/python3.6/site-packages/scoary/methods.py", line 359, in Csv_to_dic_Roary
    header[startcol]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hermuba/miniconda3/lib/python3.6/site-packages/scoary/methods.py", line 215, in main
    outdir=args.outdir)
  File "/home/hermuba/miniconda3/lib/python3.6/site-packages/scoary/methods.py", line 361, in Csv_to_dic_Roary
    sys.exit("The startcol (-s) you have specified does not seem to "
SystemExit: The startcol (-s) you have specified does not seem to correspond to any column in your gene presence/absence file.
